services:
  server:
    restart: unless-stopped
    build: ./backend
    ports: ['8080:8080']
    environment:
      - DATA_DIR=/app/data
      - PROVIDERS_WEATHER_MODE=mock
      - PROVIDERS_NEWS_MODE=mock

  web:
    restart: unless-stopped
    build: ./frontend
    ports: ['80:80']
    depends_on: [server]
